name: CI

# Controls when the action will run.
on: [ pull_request ]

jobs:
  test:
    name: Simple unit-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.4', '8.0' ]

    env:
      extensions: bcmath, iconv, ctype, gd, mbstring, mysqli, pdo, pdo_mysql, sockets, zip, soap, intl, fileinfo, json, libxml, openssl, pcntl, posix, simplexml, zend-opcache, runkit7-3.1.0a1, igbinary, redis
      key: cache-eggheads-v1

    steps:
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=./
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: PHPUnit
        run: php -dxdebug.mode=develop vendor/bin/phpunit --colors=always